# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Don't run pre-commit on files under third-party/
exclude: "^\
  (third-party/.*)\
  "
repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v18.1.0"
    hooks:
      - id: clang-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files # prevents giant files from being committed.
      - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems.
      - id: check-merge-conflict # checks for files that contain merge conflict strings.
      - id: check-yaml # checks yaml files for parseable syntax.
      - id: detect-private-key # detects the presence of private keys.
      - id: fix-byte-order-marker # removes utf-8 byte order marker.
      - id: mixed-line-ending # replaces or checks mixed line ending.
      - id: requirements-txt-fixer # sorts entries in requirements.txt.
      - id: trailing-whitespace # trims trailing whitespace.

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(js|ts|jsx|tsx|css|less|html|json|markdown|md|yaml|yml)$

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell

  # - repo: local
  #   hooks:
  #     # keep this before clang-tidy, it generates compile_commands.json for it.
  #     # requires the 'compiledb' tool, 'pip install compiledb'
  #     - id: compiledb
  #       name: compiledb
  #       entry: compiledb
  #       language: system
  #       args: [--overwrite, make, -n, -B]
  #       always_run: true
  #       require_serial: true
  #       pass_filenames: false

  # - repo: https://github.com/pocc/pre-commit-hooks
  #   rev: v1.3.5
  #   hooks:
  #     - id: clang-tidy
  #       args: [-checks=clang-diagnostic-return-type]
  #       files: src/.*\.cpp
